routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\AuthController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PostController;

use App\Models\Post;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

# Auth Routes
Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
Route::get('/login', [AuthController::class, 'loginForm'])->name('login');
Route::post('/login', [AuthController::class, 'login'])->name('login');
Route::get('/register', [AuthController::class, 'registrationForm'])->name('register');
Route::post('/register', [AuthController::class, 'registration'])->name('register');

#Admin Routes
Route::prefix('admin')->group(function () {
    
    Route::get('/roles', [AdminController::class, 'roleView']);
    Route::post('/set_role', [AdminController::class, 'setRole'])->name('set_role');

});

#User Routes
Route::prefix('user')->group(function () {
    
    Route::get('/list', [UserController::class, 'index']);
    Route::get('/{id}', [UserController::class, 'show']);

});

#Post Routes
Route::resource('posts', PostController::class);

Route::get('/', function () {
    $posts = Post::orderBy('created_at')
    ->take(4)
    ->get();
    return view('welcome',[ 'posts' => $posts]);
});

resources/views/userlist.blade.php
@extends('layouts.app')

@section('page_title')
    User List
@endsection

@section('content')

@error('setError')
    <div class="alert alert-danger">{{ $message }}</div>
@enderror

<div class="hidden fixed top-0 right-0 px-6 py-4 sm:block">
    <a href="{{ url('/') }}" class="text-sm text-gray-700 underline">Home</a>
    <a href="{{ route('logout') }}" class="text-sm text-gray-700 underline">Log out</a>

</div>

<div class="User">
    <div>
            <h3><strong>User name</strong></h3>
    </div>
    <div>
        @foreach ($users as $user)

        <div>
            <a href="{{ url('/user/').'/'.$user->id }}"><p>{{ $user->user_name }}</p>        </a>
        </div>

        @endforeach
    </div>
</div>

{{ $users->links() }}

@endsection

resources/views/userpage.blade.php
@extends('layouts.app')

@section('page_title',$user->user_name)
    
@error('general')
    <div class="alert alert-danger">{{ $message }}</div>
@enderror

@if (\Session::has('success'))
    <div class="alert alert-success">{{ \Session::get('success') }} </div>
@endif

@section('content')
<div class="relative flex items-top justify-center min-h-screen bg-gray-100 dark:bg-gray-900 sm:items-center py-4 sm:pt-0">
    
    @if (Route::has('login'))
        <div class="hidden fixed top-0 right-0 px-6 py-4 sm:block">
            <a href="{{ url('/user/list') }}" class="text-sm text-gray-700 underline">Users</a>
            @auth
                <a href="{{ url('/') }}" class="text-sm text-gray-700 underline">Home</a>
                <a href="{{ route('logout') }}" class="text-sm text-gray-700 underline">Log out</a>
            @else
                <a href="{{ route('login') }}" class="text-sm text-gray-700 underline">Log in</a>

                @if (Route::has('register'))
                    <a href="{{ route('register') }}" class="ml-4 text-sm text-gray-700 underline">Register</a>
                @endif
            @endauth
        </div>
    @endif

    <h1>{{ $user->user_name }}</h1>

    <form action="{{ route('posts.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <input type="text" name="name" placeholder="image name" required ><br>
        <input type="file" name="file" required ><br>
        <input type="submit">
    </form>
    
    @forelse  ($posts as $post)
        <div>
            <img src="{{ asset('storage'.$post->file) }}" alt="{{ $post->name }}" width="250" height="250"> 
            @can('delete',$post)
            <form action="{{ route('posts.destroy',[$post->id]) }}" method="POST">
                @method('DELETE')
                @csrf
                <button type="submit">Delete</button>               
            </form>
            @endcan
        </div>
    @empty
        <p>No posts</p>
    @endforelse 
</div>

@endsection